=== hector6933/DAM1/LenguajeDeMarcas/RepasoHector/xsdydtd/Ej1/libro.dtd
<!ELEMENT libro (autores,editorial,sinopsis,categorias?,precio?)>
<!ELEMENT autores (autor+)>

<!ELEMENT autor (nombre,apellidos,nacionalidad,biografia?,foto?,web?)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT biografia (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT web (#PCDATA)>

<!ELEMENT editorial (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

<!ELEMENT categorias (categoria*)>

<!ELEMENT categoria EMPTY>
<!ELEMENT precio (#PCDATA)>


<!ATTLIST libro isbn ID #REQUIRED>
<!ATTLIST libro idioma (es | en | fr | de) #REQUIRED>
<!ATTLIST libro formato (tapa_dura | tapa_blanda | ebook) "tapa_blanda">

<!ATTLIST autor id ID #REQUIRED>
<!ATTLIST autor rol (autor | coautor | traductor) "autor">

<!ATTLIST categoria nombre CDATA #REQUIRED>

<!ATTLIST precio moneda CDATA "EUR">

=== hector6933/DAM1/LenguajeDeMarcas/RepasoHector/xsdydtd/Ej1/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE libro SYSTEM "libro.dtd">-->
<libro isbn="ISBN-1234567890" idioma="es" formato="tapa_dura" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="libro.xsd">
    <autores>
        <autor id="A1" rol="coautor">
            <nombre></nombre>
            <apellidos></apellidos>
            <nacionalidad></nacionalidad>
            <web></web>
        </autor>
    </autores>
    <editorial></editorial>
    <sinopsis></sinopsis>
    <categorias>
        <categoria nombre=""></categoria>
        <categoria nombre=""></categoria>
        <categoria nombre=""></categoria>
    </categorias>
    <precio moneda="EUR">
        <valor>2.2</valor>
    </precio>
</libro>
